name: "Deploy to Codigofacilito"

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    step: 
      uses: actions/checkout@v4
        - run: echo "Hacemos pull del código"
        - run: echo "Correr migraciones"
        - run: echo "Generar binario"
        - run: echo "Publicar versión"