name: "Deploy to Codigofacilito"

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    step: 
      - run: echo "Hacemos pull del código"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar versión"